services:
  #db:
  #  image: postgres:15
  #  volumes:
  #    - ./api/cm-data/:/var/lib/postgresql/data/pgdata
  #  env_file:
  #    - ./api/.env
  #  environment:
  #    - PGDATA=/var/lib/postgresql/data/pgdata
  #
  #  restart:
  #    always
  #  ports:
  #    - 5432:5432
  #pgadmin:
  #  image: dpage/pgadmin4
  #  networks:
  #    - default
  #  env_file:
  #    - ./api/.env
  #  depends_on:
  #    - db
  #  ports:
  #    - 8080:80
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: starter
    restart: always
    tty: true
    env_file:
      - ./api/.env
    volumes:
    - ./api:/code/api
    #depends_on:
    #  - db
    ports:
      - "8000:8000"
